include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    depend_on_referenced_packages: ignore
    must_be_immutable: ignore
    todo: ignore
    fixme: ignore