name: hoco
description: Hoco application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.9.0+8

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  adaptive_dialog: ^1.6.4+1
  animated_button: ^0.2.0
  change_app_package_name: ^1.1.0
#  circle_checkbox: ^0.0.2+1
  configurable_expansion_tile_null_safety: ^3.3.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.3
  expansion_tile_card: ^3.0.0
  floor: ^1.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
#  flutter_screen_lock: ^9.2.0
  flutter_screenutil: ^5.5.3+2
  flutter_slider_drawer: ^2.1.1
  flutter_sms: ^2.3.3
#  flutter_sms_listener: ^0.1.3
  flutter_translate: ^4.0.3
  flutter_native_contact_picker: ^0.0.9
  fluttertoast: ^8.0.9
  fswitch_nullsafety: ^2.0.2
  get_it: ^7.2.0
  loading_animations: ^2.2.0
  local_auth: ^2.1.0
  ndialog: ^4.1.1
  permission_handler: ^10.0.0
  provider: ^6.0.3
  restart_app: ^1.1.0+1
  scrollable_positioned_list: ^0.3.2
  shamsi_date: ^1.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  signal_strength_indicator: ^0.4.1
  step_progress_indicator: ^1.0.2
  supercharged: ^2.1.1
  tokenizer:
    path: packages/tokenizer
  sms_advanced:
    path: packages/sms_advanced
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.11
  floor_generator: ^1.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  #ios: true
  image_path: "assets/images/ic_launcher.png"
  #image_path_ios: "assets/images/ic_launcher_ios.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/i18n/

  fonts:
    - family: kara
      fonts:
        - asset: assets/fonts/sgkara_regular.ttf
          weight: 400
        - asset: assets/fonts/sgkara_light.ttf
          weight: 300
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSansBold.ttf
          weight: 700
        - asset: assets/fonts/IRANSansMedium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans.ttf
          weight: 400
        - asset: assets/fonts/IRANSansLight.ttf
          weight: 300
        - asset: assets/fonts/IRANSansUltraLight.ttf
          weight: 200
